---
- name: "Add APT PBS signing key"
  become: yes
  apt_key:
    url: "{{ pbs_repo_key }}"
  when: > 
    ansible_distribution == 'Debian' and
    ansible_distribution_release == pbs_debian_release_name
  tags: ["pbs"]

- name: "Remove Enterprise PBS repository"
  become: yes
  apt_repository:
    repo: "{{ pbs_repo_enterprise_subscription }}"
    state: absent
  when: >
    ansible_distribution == 'Debian' and
    ansible_distribution_release == pbs_debian_release_name and
    pbs_use_enterprise_repos != true
  tags: ["pbs"]

- name: "Remove Enterprise PBS repository"
  become: yes
  file:
    path: "/etc/apt/sources.list.d/pbs-enterprise.list"
    state: absent
  when: >
    ansible_distribution == 'Debian' and
    ansible_distribution_release == pbs_debian_release_name and
    pbs_use_enterprise_repos != true
  tags: ["pbs"]

- name: "Add PBS repository"
  become: yes
  apt_repository:
    repo: "{{ pbs_repo_enterprise_subscription if pbs_use_enterprise_repos else pbs_repo_no_subscription }}"
    filename: pbs-enterprise
  when: >
    ansible_distribution == 'Debian' and
    ansible_distribution_release == pbs_debian_release_name
  tags: ["pbs"]

- debug:
    msg: "Installing packages, this may take a while..."
  tags: ["pbs"]

- name: "Install PBS Server packages"
  become: yes
  package:
    name: "{{ pbs_apt_packages_server }}"
    update_cache: yes
    state: latest
  when: pbs_install_server|bool
  tags: ["pbs"]

- name: "Install PBS Client packages"
  become: yes
  package:
    name: "{{ pbs_apt_packages_client }}"
    update_cache: yes
    state: latest
  when: pbs_install_client|bool
  tags: ["pbs"]